// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLg4zIvl75HUha2nOFrqrw9wsJgvI1VNk',
    appId: '1:556664956653:web:1b0c5ff37999d1b8c30ee4',
    messagingSenderId: '556664956653',
    projectId: 'mynotessch',
    authDomain: 'mynotessch.firebaseapp.com',
    storageBucket: 'mynotessch.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcClN9qJ35ZmfUVC35GlpfYpe68g4x6u0',
    appId: '1:556664956653:android:a2ef3c738c311fa3c30ee4',
    messagingSenderId: '556664956653',
    projectId: 'mynotessch',
    storageBucket: 'mynotessch.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQK9OiozEszphyCoPs2MkhPJh4nsOYwwc',
    appId: '1:556664956653:ios:6547e1a5171e1815c30ee4',
    messagingSenderId: '556664956653',
    projectId: 'mynotessch',
    storageBucket: 'mynotessch.appspot.com',
    iosClientId: '556664956653-54lu232p5gfdhupto1dlk8qlt6dlrqdr.apps.googleusercontent.com',
    iosBundleId: 'com.SCH.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQK9OiozEszphyCoPs2MkhPJh4nsOYwwc',
    appId: '1:556664956653:ios:6547e1a5171e1815c30ee4',
    messagingSenderId: '556664956653',
    projectId: 'mynotessch',
    storageBucket: 'mynotessch.appspot.com',
    iosClientId: '556664956653-54lu232p5gfdhupto1dlk8qlt6dlrqdr.apps.googleusercontent.com',
    iosBundleId: 'com.SCH.mynotes',
  );
}
